CREATE TABLE CATEGORY (
       ID INT NOT NULL AUTO_INCREMENT
     , NAME VARCHAR(100) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
       ID INT NOT NULL AUTO_INCREMENT
     , CATEGORY_ID INT NOT NULL
     , ISBN VARCHAR(10) NOT NULL
     , TITLE VARCHAR(500) NOT NULL
     , PRICE DECIMAL(4,2)
     , PRIMARY KEY (ID)
     , CONSTRAINT FK_BOOK FOREIGN KEY (CATEGORY_ID)
                   REFERENCES CATEGORY (ID)
);

CREATE TABLE AUTHOR (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(60) NOT NULL
     , DESCRIPTION VARCHAR(1200) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE  AUTHOR_BOOK (
    AUTHOR_ID INTEGER NOT NULL,
    BOOK_ID INTEGER NOT NULL,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK (ID) ON DELETE RESTRICT ON UPDATE CASCADE,
    PRIMARY KEY (AUTHOR_ID, BOOK_ID)
);

